version: "3.8"
services:
  discord-bot:
    image: barodev/baro-bot-discord:0.0.1-SNAPSHOT
    container_name: discord-bot
    hostname: discord-bot
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - local-network
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    networks:
      - local-network
  redis:
    image: redis:alpine3.12
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redist-data-volume:/data
    networks:
      - local-network
networks:
  local-network:
volumes:
  postgres-data-volume:
  redist-data-volume: