version: "3.8"
services:
  barobot-discord:
    image: barodev/baro-bot-discord:0.0.3
    container_name: barobot-discord
    hostname: barobot-discord
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - barobot-postgres
      - barobot-redis
    networks:
      - barobot-local-network
  barobot-postgres:
    image: postgres
    hostname: barobot-postgres
    container_name: barobot-postgres
    restart: always
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - barobot-postgres-data:/var/lib/postgresql/data
    networks:
      - barobot-local-network
  barobot-redis:
    image: redis:alpine3.12
    container_name: barobot-redis
    hostname: barobot-redis
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${SPRING_REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - barobot-redist-data:/data
    #      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - barobot-local-network
networks:
  barobot-local-network:
volumes:
  barobot-postgres-data:
  barobot-redist-data: